#spring.profiles: andr
socket:
  host: 127.0.0.1
  port: 7777


logging:
  file.name: logs/-egts-parser-data-andr.log
  file.max-size: 1MB

  level:
    org.springframework: error
    ru.tnt: trace
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"

threads: 30
validate: true