socket:
  host: 127.0.0.1
  port: 5555


threads: 50
validate: true

logging:
  file.name: logs/-egts-parser-data.log
  file.max-size: 1MB

  level:
    org.springframework: error
    ru.tnt: trace
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
