socket:
  host: 127.0.0.1
  port: 5555


#spring:
#  profiles:
#    active: "dev"

logging:
  file: logs/app.log
  level:
    org.springframework: off
    ru.tnt: trace
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
